# Generated by Django 6.0.5 on 2026-05-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('problem_url', models.URLField(blank=True, null=True)),
                ('platform', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10)),
                ('solution_notes', models.TextField(blank=True, null=True)),
                ('date_solved', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
